package io.github.truenine.composeserver.ksp.meta.annotations

import java.lang.annotation.Inherited

/**
 * ## Enable automatic management by the program
 * > Delegate control of the element to other self-management mechanisms.
 *
 * Informs the compiler that this element should not be manually managed, but instead handled by other mechanisms such as frameworks or post-processing, and
 * should not be interfered with by user code. For example, database metadata fields should be automatically generated by the database or post-processing steps,
 * rather than being manually controlled in the business logic layer. These typically include:
 * - Primary keys
 * - Auto-generated order numbers
 * - Logical delete flags
 * - Table creation time
 * - Table modification time
 *
 * And other similar database metadata fields.
 *
 * @author TrueNine
 * @since 2024-12-02
 */
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.FIELD, AnnotationTarget.PROPERTY_GETTER, AnnotationTarget.PROPERTY_SETTER)
@Retention(AnnotationRetention.BINARY)
@MustBeDocumented
@Inherited
annotation class MetaAutoManagement
