spring:
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "#Pengjigong1997"
    url: "jdbc:mysql://116.205.171.51:3306/acin_db_v1"
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
