package io.github.truenine.composeserver.security.crypto

import io.github.truenine.composeserver.security.crypto.domain.*
import io.github.truenine.composeserver.slf4j
import javax.crypto.spec.SecretKeySpec

private val log = slf4j<AutoGeneratedKeysRepo>()

class AutoGeneratedKeysRepo : IKeysRepo {
  private val aesKey = CryptographicKeyManager.generateAesKey()
  private val rsaKeyPair = CryptographicKeyManager.generateRsaKeyPair()
  private val eccKeyPair = CryptographicKeyManager.generateEccKeyPair(CryptographicKeyManager.generateRandomAsciiString())

  init {
    log.warn("Warning: using auto-generated KeyRepository; keys will change on each startup")
  }

  override fun basicAesKey(): SecretKeySpec? = aesKey

  override fun basicRsaKeyPair(): IRsaExtKeyPair? = rsaKeyPair

  override fun basicEccKeyPair(): IEccExtKeyPair? = eccKeyPair
}
