package net.yan100.compose.core.encrypt


import net.yan100.compose.core.lang.slf4j
import javax.crypto.spec.SecretKeySpec

class AutoGeneratedKeysRepository : KeysRepository {
  private val aesKey = Keys.generateAesKey()
  private val rsaKeyPair = Keys.generateRsaKeyPair()
  private val eccKeyPair = Keys.generateEccKeyPair()

  init {
    log.warn("警告：程序正在使用一次性生成的 keys 仅供一次性测试使用")
  }

  override fun basicAesKey(): SecretKeySpec? {
    return aesKey
  }

  override fun basicRsaKeyPair(): RsaKeyPair? {
    return rsaKeyPair
  }

  override fun basicEccKeyPair(): EccKeyPair? {
    return eccKeyPair
  }

  companion object {
    private val log = slf4j(AutoGeneratedKeysRepository::class)
  }
}
