package net.yan100.compose.core.encrypt


import net.yan100.compose.core.lang.slf4j
import javax.crypto.spec.SecretKeySpec

class AutoGeneratedKeysRepo : IKeysRepo {
  companion object {
    private val log = slf4j(AutoGeneratedKeysRepo::class)
  }

  private val aesKey = Keys.generateAesKey()
  private val rsaKeyPair = Keys.generateRsaKeyPair()
  private val eccKeyPair = Keys.generateEccKeyPair()

  init {
    log.warn("警告：正在使用一次性生成的 KeyRepository，该提供程序每次启动都会变化")
  }

  override fun basicAesKey(): SecretKeySpec? {
    return aesKey
  }

  override fun basicRsaKeyPair(): RsaKeyPair? {
    return rsaKeyPair
  }

  override fun basicEccKeyPair(): EccKeyPair? {
    return eccKeyPair
  }
}
