package net.yan100.compose.security.crypto

import net.yan100.compose.core.domain.enc.EccKeyPair
import net.yan100.compose.core.domain.enc.RsaKeyPair
import net.yan100.compose.core.slf4j
import net.yan100.compose.security.crypto.domain.IEccExtKeyPair
import net.yan100.compose.security.crypto.domain.IKeysRepo
import net.yan100.compose.security.crypto.domain.IRsaExtKeyPair
import javax.crypto.spec.SecretKeySpec

private val log = slf4j<AutoGeneratedKeysRepo>()

class AutoGeneratedKeysRepo : IKeysRepo {
  private val aesKey = Keys.generateAesKey()
  private val rsaKeyPair = Keys.generateRsaKeyPair()
  private val eccKeyPair = Keys.generateEccKeyPair()

  init {
    log.warn("警告：正在使用一次性生成的 KeyRepository，该提供程序每次启动都会变化")
  }

  override fun basicAesKey(): SecretKeySpec? = aesKey
  override fun basicRsaKeyPair(): IRsaExtKeyPair? = rsaKeyPair
  override fun basicEccKeyPair(): IEccExtKeyPair? = eccKeyPair
}
