compose:
  mqtt:
    url: tcp://116.205.171.51:1883
    username: test
    password: qwerty123456
    client-id: springBoot
    topics:
      - topic/test1
      - topic/test2
      - topic/test3
    connect-timeout-second: 10
    keep-alive-second: 10
  web-api-doc:
    open-api:
      scan-packages: io.tnt
spring:
  threads:
    virtual:
      enabled: true
