name: 'Gradle Execute'
description: 'Execute Gradle commands with consistent configuration'
inputs:
  tasks:
    description: 'Gradle tasks to execute (space-separated)'
    required: true
  parallel:
    description: 'Enable parallel execution'
    required: false
    default: 'true'
  build-cache:
    description: 'Enable build cache'
    required: false
    default: 'true'
  configuration-cache:
    description: 'Enable configuration cache'
    required: false
    default: 'true'
  max-workers:
    description: 'Maximum worker count'
    required: false
    default: '4'
  timeout:
    description: 'Timeout in minutes'
    required: false
    default: '30'
  continue-on-error:
    description: 'Continue on error'
    required: false
    default: 'false'
  working-directory:
    description: 'Working directory for Gradle execution'
    required: false
    default: '.'
outputs:
  success:
    description: 'Whether execution succeeded'
    value: ${{ steps.exec.outputs.success }}
  output:
    description: 'Command output'
    value: ${{ steps.exec.outputs.output }}
  exit-code:
    description: 'Exit code of the Gradle command'
    value: ${{ steps.exec.outputs.exit-code }}
runs:
  using: 'composite'
  steps:
    - name: Execute Gradle
      id: exec
      shell: bash
      env:
        INPUT_TASKS: ${{ inputs.tasks }}
        INPUT_PARALLEL: ${{ inputs.parallel }}
        INPUT_BUILD_CACHE: ${{ inputs.build-cache }}
        INPUT_CONFIGURATION_CACHE: ${{ inputs.configuration-cache }}
        INPUT_MAX_WORKERS: ${{ inputs.max-workers }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_CONTINUE_ON_ERROR: ${{ inputs.continue-on-error }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: node ${{ github.action_path }}/dist/index.js
