package net.yan100.compose.security.crypto.autoconfig

import net.yan100.compose.security.crypto.AutoGeneratedKeysRepo
import net.yan100.compose.security.crypto.domain.IKeysRepo
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

@Configuration
class KeyRepositoryAutoconfiguration {
  @Bean @ConditionalOnMissingBean(IKeysRepo::class) fun autoGenerateKeys(): IKeysRepo = AutoGeneratedKeysRepo()
}
