[plugins]
compose-version-control = { id = "net.yan100.compose.version-control", version.ref = "compose-version-control-plugin" }
kt-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kt-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kt-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kt-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "kotlin" }
kt-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-boot-dependencymanagement = { id = "io.spring.dependency-management", version.ref = "gradle-plugin-spring-boot-dependencymanagement" }
hibernate-orm = { id = "org.hibernate.orm", version.ref = "hibernate" }
versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-plugin-version-plugin" }
ascijvm-convert = { id = "org.asciidoctor.jvm.convert", version.ref = "gradle-plugin-ascijvm-convert" }

[bundles]
spring-kotlin-testng = ["spring-boot-test", "spring-security-test", "spring-modulith-test", "test-kt-testng", "test-mockk", "test-testng", "db-hsql", "db-sqlite"]
kt = ["kt-stdlib-jdk8", "kt-reflact", "ktx-coroutine-reactor", "reactor-kt-extensions", "jbr-annotation"]
p6spy-starter = ["db-p6spy-starter", "db-p6spy"]



[libraries]
compose-core = { group = "net.yan100.compose", name = "core", version.ref = "compose-core" }
compose-rds = { group = "net.yan100.compose", name = "rds", version.ref = "compose-rds" }
compose-rds-gen = { group = "net.yan100.compose", name = "rds-gen", version.ref = "compose-rds-gen" }
compose-oss = { group = "net.yan100.compose", name = "oss", version.ref = "compose-oss" }
compose-security = { group = "net.yan100.compose", name = "security", version.ref = "compose-security-oauth2" }
compose-security-oauth2 = { group = "net.yan100.compose", name = "security-oauth2", version.ref = "compose-security" }
compose-pay = { group = "net.yan100.compose", name = "pay", version.ref = "compose-pay" }
compose-schedule = { group = "net.yan100.compose", name = "schedule", version.ref = "compose-schedule" }
compose-webapidoc = { group = "net.yan100.compose", name = "web-api-doc", version.ref = "compose-webapidoc" }
compose-cacheable = { group = "net.yan100.compose", name = "cacheable", version.ref = "compose-cacheable" }
compose-datacommon-cralwer = { group = "net.yan100.compose", name = "data-common-cralwer", version.ref = "compose-datacommon-cralwer" }
compose-datacommon-dataextract = { group = "net.yan100.compose", name = "data-common-data-extract", version.ref = "compose-datacommon-dataextract" }
compose-depend-flyway = { group = "net.yan100.compose", name = "depend-flyway", version.ref = "compose-depend-flyway" }
compose-depend-webservlet = { group = "net.yan100.compose", name = "depend-web-servlet", version.ref = "compose-depend-webservlet" }
compose-depend-webclient = { group = "net.yan100.compose", name = "depend-web-client", version.ref = "compose-depend-webclient" }

spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-security-test = { group = "org.springframework.security", name = "spring-security-test" }
spring-modulith-test = { group = "org.springframework.modulith", name = "spring-modulith-starter-test" }

kt-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kt-reflact = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
ktx-coroutine-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "ktx-coroutine" }
reactor-kt-extensions = { group = "io.projectreactor.kotlin", name = "reactor-kotlin-extensions", version.ref = "reactor-kt-extensions" }
jbr-annotation = { group = "org.jetbrains", name = "annotations", version.ref = "jbr-annotation" }

test-mockk = { group = "io.mockk", name = "mockk", version.ref = "test-mockk" }
test-testng = { group = "org.testng", name = "testng", version.ref = "test-testng" }
test-reactor-test = { group = "io.projectreactor", name = "reactor-test" }

db-hsql = { group = "org.hsqldb", name = "hsqldb", version.ref = "db-hsql" }
db-sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "db-sqlite" }
db-mysql-j = { group = "com.mysql", name = "mysql-connector-j", version.ref = "db-mysql-j" }

db-p6spy = { group = "p6spy", name = "p6spy", version.ref = "db-p6spy" }
db-p6spy-starter = { group = "com.github.gavlyukovskiy", name = "p6spy-spring-boot-starter", version.ref = "db-p6spy-starter" }

test-kt-testng = { group = "org.jetbrains.kotlin", name = "kotlin-test-testng", version.ref = "kotlin" }

util-guava-jre = { group = "com.google.guava", name = "guava", version.ref = "util-guava-jre" }
util-guava-android = { group = "com.google.guava", name = "guava", version.ref = "util-guava-android" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

bom-spring-modulith = { group = "org.springframework.modulith", name = "spring-modulith-bom", version.ref = "spring-modulith" }
bom-spring-boot = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
bom-spring-cloud = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "spring-cloud" }
bom-spring-cloudalibaba = { group = "com.alibaba.cloud", name = "spring-cloud-alibaba-dependencies", version.ref = "spring-cloudalibaba" }

[versions]
compose = "0.6.55"
compose-core = "0.6.55"
compose-rds = "0.6.55"
compose-rds-gen = "0.6.55"
compose-oss = "0.6.55"
compose-pay = "0.6.55"
compose-schedule = "0.6.55"
compose-security = "0.6.55"
compose-security-oauth2 = "0.6.55"
compose-webapidoc = "0.6.55"
compose-cacheable = "0.6.55"
compose-datacommon-cralwer = "0.6.55"
compose-datacommon-dataextract = "0.6.55"
compose-depend-flyway = "0.6.55"
compose-depend-webservlet = "0.6.55"
compose-depend-webclient = "0.6.55"
compose-version-control-plugin = "1.1.24"


java = "17"
kotlin = "1.9.10"
ktx-coroutine = "1.7.3"
reactor-kt-extensions = "1.2.2"
jbr-annotation = "24.0.1"
spring-boot = "3.1.3"
spring-cloud = "2022.0.4"
spring-cloudalibaba = "2021.0.4.0"
spring-modulith = "1.0.0"

gradle = "8.3"
# https://github.com/ben-manes/gradle-versions-plugin
gradle-plugin-version-plugin = "0.48.0"
gradle-plugin-spring-boot-dependencymanagement = "1.1.3"
# https://mvnrepository.com/artifact/org.asciidoctor.jvm.convert/org.asciidoctor.jvm.convert.gradle.plugin?repo=gradle-plugins
gradle-plugin-ascijvm-convert = "3.3.2"

test-testng = "7.8.0"
test-mockk = "1.13.7"
test-junit = "5.10.0"


db-hsql = "2.7.2"
db-sqlite = "3.43.0.0"
db-mysql-j = "8.1.0"
db-p6spy = "3.9.1"
db-p6spy-starter = "1.9.0"

util-hutool = "5.8.22"
util-guava-jre = "32.1.2-jre"
util-guava-android = "32.1.2-android"
lombok = "1.18.28"

hibernate = "6.2.7.Final"
