[plugins]
compose-versioncontrol = { id = "net.yan100.compose.version-control", version.ref = "compose" }
kt-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kt-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kt-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kt-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "kotlin" }
kt-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-boot-dependencymanagement = { id = "io.spring.dependency-management", version.ref = "gradle-plugin-spring-boot-dependencymanagement" }
hibernate-orm = { id = "org.hibernate.orm", version.ref = "hibernate" }
versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-plugin-version-plugin" }
graalvm = { id = "org.graalvm.buildtools.native", version.ref = "gradle-plugin-graalvm-native" }
ascijvm-convert = { id = "org.asciidoctor.jvm.convert", version.ref = "gradle-plugin-ascijvm-convert" }

[bundles]
spring-kotlin-testng = ["spring-boot-test", "test-spring-security-test", "test-spring-modulith-test", "test-kt-testng", "test-mockk", "test-testng", "db-hsql", "db-sqlite"]
kt = ["kt-stdlib", "kt-reflact", "ktx-coroutine-reactor", "reactor-kt-extensions", "jbr-annotation", "jackson-module-kotlin"]
p6spystarter = ["db-p6spy-starter", "db-p6spy"]
spring-boot-data-redis = ["spring-boot-data-redis", "spring-boot-data-redis-reactive", "apache-commons-pool2"]
spring-boot-data-jpa = ["spring-boot-data-jpa", "spring-modulith-jpa"]
selenium = ["cralwer-selenium-java", "cralwer-selenium-webdrivermanager"]
flyway = ["db-flyway-mysql", "db-flyway-core"]
knife4j = ["sdk-openapi-knife4jjakarta", "spring-doc-webmvc-ui3"]

[libraries]
compose-core = { group = "net.yan100.compose", name = "core", version.ref = "compose" }
compose-rds = { group = "net.yan100.compose", name = "rds", version.ref = "compose" }
compose-rds-gen = { group = "net.yan100.compose", name = "rds-gen", version.ref = "compose" }
compose-oss = { group = "net.yan100.compose", name = "oss", version.ref = "compose" }
compose-security = { group = "net.yan100.compose", name = "security", version.ref = "compose" }
compose-security-oauth2 = { group = "net.yan100.compose", name = "security-oauth2", version.ref = "compose" }
compose-pay = { group = "net.yan100.compose", name = "pay", version.ref = "compose" }
compose-schedule = { group = "net.yan100.compose", name = "schedule", version.ref = "compose" }
compose-webapidoc = { group = "net.yan100.compose", name = "web-api-doc", version.ref = "compose" }
compose-cacheable = { group = "net.yan100.compose", name = "cacheable", version.ref = "compose" }
compose-datacommon-cralwer = { group = "net.yan100.compose", name = "data-common-cralwer", version.ref = "compose" }
compose-datacommon-dataextract = { group = "net.yan100.compose", name = "data-common-data-extract", version.ref = "compose" }
compose-depend-mqtt = { group = "net.yan100.compose", name = "depend-mqtt", version.ref = "compose" }
compose-depend-flyway = { group = "net.yan100.compose", name = "depend-flyway", version.ref = "compose" }
compose-depend-webservlet = { group = "net.yan100.compose", name = "depend-web-servlet", version.ref = "compose" }
compose-depend-webclient = { group = "net.yan100.compose", name = "depend-web-client", version.ref = "compose" }

spring-boot-autoconfigure = { group = "org.springframework.boot", name = "spring-boot-autoconfigure" }
spring-boot-configureprocessor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-json = { group = "org.springframework.boot", name = "spring-boot-starter-json" }
spring-boot-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-boot-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-websocket = { group = "org.springframework.boot", name = "spring-boot-starter-websocket" }
spring-boot-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-undertow = { group = "org.springframework.boot", name = "spring-boot-starter-undertow" }
spring-boot-data-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis" }
spring-boot-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-data-redis-reactive = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis-reactive" }
spring-boot-logging = { group = "org.springframework.boot", name = "spring-boot-starter-logging" }

spring-cloud-bootstrap = { group = "org.springframework.cloud", name = "spring-cloud-starter-bootstrap" }

spring-integration-mqtt = { group = "org.springframework.integration", name = "spring-integration-mqtt" }

spring-security-crypto = { group = "org.springframework.security", name = "spring-security-crypto" }
spring-security-core = { group = "org.springframework.security", name = "spring-security-core" }
spring-webmvc = { group = "org.springframework", name = "spring-webmvc" }
spring-modulith-jpa = { group = "org.springframework.modulith", name = "spring-modulith-starter-jpa" }
spring-modulith-core = { group = "org.springframework.modulith", name = "spring-modulith-core", version.ref = "spring-modulith" }
spring-doc-webmvc-ui3 = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "spring-doc-webmvc-ui3" }


apache-commons-pool2 = { group = "org.apache.commons", name = "commons-pool2", version.ref = "apache-commons-pool2" }
apache-commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "apache-commons-compress" }

kt-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kt-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kt-reflact = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
ktx-coroutine-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "ktx-coroutine" }
reactor-kt-extensions = { group = "io.projectreactor.kotlin", name = "reactor-kotlin-extensions", version.ref = "reactor-kt-extensions" }
jbr-annotation = { group = "org.jetbrains", name = "annotations", version.ref = "jbr-annotation" }

test-mockk = { group = "io.mockk", name = "mockk", version.ref = "test-mockk" }
test-testng = { group = "org.testng", name = "testng", version.ref = "test-testng" }
test-kt-testng = { group = "org.jetbrains.kotlin", name = "kotlin-test-testng", version.ref = "kotlin" }
test-reactor-test = { group = "io.projectreactor", name = "reactor-test" }
test-spring-security-test = { group = "org.springframework.security", name = "spring-security-test" }
test-spring-modulith-test = { group = "org.springframework.modulith", name = "spring-modulith-starter-test" }

db-hsql = { group = "org.hsqldb", name = "hsqldb", version.ref = "db-hsql" }
db-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "db-postgresql" }
db-sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "db-sqlite" }
db-mysql-j = { group = "com.mysql", name = "mysql-connector-j", version.ref = "db-mysql-j" }
db-supercsv = { group = "net.sf.supercsv", name = "super-csv", version.ref = "db-supercsv" }
db-flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "db-flyway" }
db-flyway-mysql = { group = "org.flywaydb", name = "flyway-mysql", version.ref = "db-flyway" }
db-p6spy = { group = "p6spy", name = "p6spy", version.ref = "db-p6spy" }
db-p6spy-starter = { group = "com.github.gavlyukovskiy", name = "p6spy-spring-boot-starter", version.ref = "db-p6spy-starter" }
db-hutool-db = { group = "cn.hutool", name = "hutool-db", version.ref = "util-hutool" }

sdk-oss-minio = { group = "io.minio", name = "minio", version.ref = "sdk-oss-minio" }
sdk-oss-aliyun = { group = "com.aliyun.oss", name = "aliyun-sdk-oss", version.ref = "sdk-oss-aliyun" }
sdk-oss-huaweicloud = { group = "com.huaweicloud", name = "esdk-obs-java", version.ref = "sdk-oss-huaweicloud" }
sdk-pay-wechatv3 = { group = "com.github.wechatpay-apiv3", name = "wechatpay-java", version.ref = "sdk-pay-wechatv3" }
sdk-openapi-knife4jjakarta = { group = "com.github.xiaoymin", name = "knife4j-openapi3-jakarta-spring-boot-starter", version.ref = "sdk-openapi-knife4jjakarta" }
sdk-openapi-knife4j = { group = "com.github.xiaoymin", name = "knife4j-spring-boot-starter", version.ref = "sdk-openapi-knife4j" }

jakarta-servlet-api = { group = "jakarta.servlet", name = "jakarta.servlet-api", version.ref = "jakarta-servlet-api" }
jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakarta-validation-api" }
jakarta-openapi-v3-annotations = { group = "io.swagger.core.v3", name = "swagger-annotations-jakarta", version.ref = "jakarta-openapi-v3-annotations" }

net-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "net-okhttp3" }

util-guava-jre = { group = "com.google.guava", name = "guava", version.ref = "util-guava-jre" }
util-guava-android = { group = "com.google.guava", name = "guava", version.ref = "util-guava-android" }
util-ognl = { group = "ognl", name = "ognl", version.ref = "util-ognl" }
util-ikanalyzer = { group = "com.github.magese", name = "ik-analyzer", version.ref = "util-ikanalyzer" }
util-smilemath = { group = "com.github.haifengl", name = "smile-math", version.ref = "util-smilemath" }
util-easyexcel = { group = "com.alibaba", name = "easyexcel", version.ref = "util-easyexcel" }
util-freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "util-freemarker" }
util-hutool-all = { group = "cn.hutool", name = "hutool-all", version.ref = "util-hutool" }
util-hutool-core = { group = "cn.hutool", name = "hutool-core", version.ref = "util-hutool" }

security-bcprov-jdk18on = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "security-bcprov-jdk18on" }
security-hutool-captcha = { group = "cn.hutool", name = "hutool-captcha", version.ref = "util-hutool" }
security-hutool-crypto = { group = "cn.hutool", name = "hutool-crypto", version.ref = "util-hutool" }
security-jwt-auth0 = { group = "com.auth0", name = "java-jwt", version.ref = "security-jwt-auth0" }
security-antisamy = { group = "org.owasp.antisamy", name = "antisamy", version.ref = "security-antisamy" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-api" }

cralwer-selenium-java = { group = "org.seleniumhq.selenium", name = "selenium-java", version.ref = "cralwer-selenium-java" }
cralwer-selenium-webdrivermanager = { group = "io.github.bonigarcia", name = "webdrivermanager", version.ref = "cralwer-selenium-webdrivermanager" }
cralwer-playwright = { group = "com.microsoft.playwright", name = "playwright", version.ref = "cralwer-playwrite" }
cralwer-jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "cralwer-jsoup" }
cralwer-nekohtml = { group = "org.htmlunit:neko-htmlunit", name = "neko-htmlunit", version.ref = "cralwer-nekohtml" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-core-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }

bom-spring-modulith = { group = "org.springframework.modulith", name = "spring-modulith-bom", version.ref = "spring-modulith" }
bom-spring-boot = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
bom-spring-cloud = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "spring-cloud" }
bom-spring-cloudalibaba = { group = "com.alibaba.cloud", name = "spring-cloud-alibaba-dependencies", version.ref = "spring-cloudalibaba" }




[versions]
compose = "1.6.87"

java = "21"
kotlin = "1.9.20-RC"
ktx-coroutine = "1.7.3"
reactor-kt-extensions = "1.2.2"
jbr-annotation = "24.0.1"

spring-boot = "3.2.0-RC1"
spring-cloud = "2023.0.0-M2"
spring-cloudalibaba = "2021.0.4.0"
spring-modulith = "1.1.0-M1"
spring-doc-webmvc-ui3 = "2.2.0"
apache-commons-pool2 = "2.12.0"
apache-commons-compress = "1.24.0"

gradle = "8.4"
gradle-plugin-version-plugin = "0.49.0"
gradle-plugin-spring-boot-dependencymanagement = "1.1.3"
gradle-plugin-ascijvm-convert = "3.3.2"
gradle-plugin-graalvm-native = "0.9.27"

net-okhttp3 = "5.0.0-alpha.11"

test-testng = "7.8.0"
test-mockk = "1.13.8"
test-junit = "5.10.0"


db-hsql = "2.7.2"
db-postgresql = "42.6.0"
db-sqlite = "3.43.2.1"
db-mysql-j = "8.1.0"
db-supercsv = "2.4.0"
db-flyway = "9.22.3"
db-p6spy = "3.9.1"
db-p6spy-starter = "1.9.0"

sdk-oss-minio = "8.5.6"
sdk-oss-aliyun = "3.17.1"
sdk-oss-huaweicloud = "3.23.9"
sdk-pay-wechatv3 = "0.2.12"
sdk-openapi-knife4jjakarta = "4.3.0"
sdk-openapi-knife4j = "3.0.3"

security-bcprov-jdk18on = "1.76"
security-jwt-auth0 = "4.4.0"
security-antisamy = "1.7.4"

util-hutool = "5.8.22"
util-guava-jre = "32.1.3-jre"
util-guava-android = "32.1.2-android"
util-ognl = "3.4.2"
util-ikanalyzer = "8.5.0"
util-smilemath = "2.6.0"
util-easyexcel = "3.3.2"
util-freemarker = "2.3.32"

slf4j-api = "2.0.9"

cralwer-selenium-java = "4.14.1"
cralwer-selenium-webdrivermanager = "5.5.3"
cralwer-playwrite = "1.39.0"
cralwer-jsoup = "1.16.2"
cralwer-nekohtml = "3.5.0"

jakarta-servlet-api = "6.0.0"
jakarta-validation-api = "3.0.2"
jakarta-openapi-v3-annotations = "2.2.17"

jackson = "2.15.2"
jackson-module-kotlin = "2.15.2"
jackson-core-annotations = "2.15.2"

lombok = "1.18.30"

hibernate = "6.3.1.Final"
