name: 'Publish Report Generator'
description: 'Generate publication reports for Maven Central publishing'
inputs:
  report-type:
    description: 'Type of report to generate: pre-publish, summary, failure'
    required: true
  version:
    description: 'Version being published'
    required: true
  group-id:
    description: 'Maven group ID'
    required: false
    default: 'io.github.truenine'
  artifacts:
    description: 'Comma-separated list of artifacts'
    required: false
    default: ''
  publish-success:
    description: 'Whether publish was successful (for summary report)'
    required: false
    default: true
  error-message:
    description: 'Error message (for failure report)'
    required: false
    default: ''
  error-details:
    description: 'Detailed error information (for failure report)'
    required: false
    default: ''
  repository-url:
    description: 'GitHub repository URL'
    required: false
    default: ''
  release-url:
    description: 'GitHub release URL'
    required: false
    default: ''
outputs:
  report:
    description: 'Generated report content'
    value: ${{ steps.generate.outputs.report }}
  report-type:
    description: 'Type of report generated'
    value: ${{ steps.generate.outputs.report-type }}
runs:
  using: 'composite'
  steps:
    - name: Generate Report
      id: generate
      shell: bash
      env:
        INPUT_REPORT_TYPE: ${{ inputs.report-type }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_GROUP_ID: ${{ inputs.group-id }}
        INPUT_ARTIFACTS: ${{ inputs.artifacts }}
        INPUT_PUBLISH_SUCCESS: ${{ inputs.publish-success }}
        INPUT_ERROR_MESSAGE: ${{ inputs.error-message }}
        INPUT_ERROR_DETAILS: ${{ inputs.error-details }}
        INPUT_REPOSITORY_URL: ${{ inputs.repository-url }}
        INPUT_RELEASE_URL: ${{ inputs.release-url }}
      run: node ${{ github.action_path }}/dist/index.js
