package io.github.truenine.composeserver.security.crypto.autoconfig

import io.github.truenine.composeserver.security.crypto.AutoGeneratedKeysRepo
import io.github.truenine.composeserver.security.crypto.domain.IKeysRepo
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

@Configuration
class KeyRepositoryAutoconfiguration {
  @Bean @ConditionalOnMissingBean(IKeysRepo::class) fun autoGenerateKeys(): IKeysRepo = AutoGeneratedKeysRepo()
}
