package io.github.truenine.composeserver.security.crypto

import io.github.truenine.composeserver.security.crypto.domain.IEccExtKeyPair
import io.github.truenine.composeserver.security.crypto.domain.IKeysRepo
import io.github.truenine.composeserver.security.crypto.domain.IRsaExtKeyPair
import io.github.truenine.composeserver.slf4j
import javax.crypto.spec.SecretKeySpec

private val log = slf4j<AutoGeneratedKeysRepo>()

class AutoGeneratedKeysRepo : IKeysRepo {
  private val aesKey = Keys.generateAesKey()
  private val rsaKeyPair = Keys.generateRsaKeyPair()
  private val eccKeyPair = Keys.generateEccKeyPair()

  init {
    log.warn("警告：正在使用一次性生成的 KeyRepository，该提供程序每次启动都会变化")
  }

  override fun basicAesKey(): SecretKeySpec? = aesKey

  override fun basicRsaKeyPair(): IRsaExtKeyPair? = rsaKeyPair

  override fun basicEccKeyPair(): IEccExtKeyPair? = eccKeyPair
}
